(() => {
  const mount = document.querySelector('#world-canvas');
  const status = document.querySelector('#world-status');
  const title = document.querySelector('#world-title');
  const copy = document.querySelector('#world-copy');
  if (!window.THREE) { status.textContent = 'WebGL saknas — använd textalternativen nedan.'; return; }
  const worlds = {
    castle: { title:'Slottet / akademin', copy:'Fyra rum att upptäcka: Gallery, Workshop, Library och Observatory.', sky:0x171927, ground:0x3a3542, image:'assets/min-varld/castle-hall.png', spots:[['Gallery',-7,-5],['Workshop',7,-5],['Library',-7,-13],['Observatory',7,-13]] },
    hotel: { title:'Hotellet', copy:'Gå från den varma korridoren ut till innergården och fontänen.', sky:0x241a19, ground:0x624737, image:'assets/min-varld/hotel-corridor.png', spots:[['Reception',-7,-5],['Innergård',7,-5],['Fontän',0,-14]] },
    forest: { title:'Skogen', copy:'En low-poly skog med berg, stigar och en utsiktsplats.', sky:0x13262b, ground:0x294638, image:'assets/min-varld/forest-reference.png', spots:[['Stigen',-7,-5],['Bergsvy',7,-10],['Utsikten',0,-16]] }
  };
  let world = new URLSearchParams(location.search).get('world') || 'castle';
  let scene, camera, renderer, group, avatar, portal, cars = [], keys = {}, drag=false, lastX=0, yaw=0;
  const tex = new THREE.TextureLoader();
  const mat = c => new THREE.MeshStandardMaterial({color:c, roughness:.86, metalness:.05});
  const box = (x,y,z,c,pos=[0,0,0]) => { const m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),mat(c)); m.position.set(pos[0],pos[1]+y/2,pos[2]); group.add(m); return m; };
  const billboard = (url, pos, scale, label) => { const m=new THREE.Mesh(new THREE.PlaneGeometry(scale[0],scale[1]),new THREE.MeshBasicMaterial({map:tex.load(url),transparent:true,side:THREE.DoubleSide})); m.position.set(...pos); m.userData.label=label; group.add(m); return m; };
  function tree(x,z){ box(.42,2,.42,0x704935,[x,0,z]); const t=new THREE.Mesh(new THREE.ConeGeometry(1.5,3,5),mat(0x3d7452)); t.position.set(x,3,z); group.add(t); }
  function car(label,x,z,color){ const root=new THREE.Group(); root.position.set(x,.05,z); root.userData={label}; const body=new THREE.Mesh(new THREE.BoxGeometry(1.8,.45,1),mat(color)); body.position.y=.45; root.add(body); const roof=new THREE.Mesh(new THREE.BoxGeometry(.9,.35,.85),mat(0xdfe7ed)); roof.position.y=.82; root.add(roof); [-.6,.6].forEach(px=>[-.42,.42].forEach(pz=>{const w=new THREE.Mesh(new THREE.CylinderGeometry(.18,.18,.12,12),mat(0x171923));w.rotation.z=Math.PI/2;w.position.set(px,.23,pz);root.add(w)})); group.add(root); cars.push(root); return root; }
  function fitAsset(root,size,position){ const b=new THREE.Box3().setFromObject(root), s=b.getSize(new THREE.Vector3()), max=Math.max(s.x,s.y,s.z)||1; const k=size/max; root.scale.multiplyScalar(k); const b2=new THREE.Box3().setFromObject(root); root.position.set(position[0],position[1]-b2.min.y,position[2]); return root; }
  function build(){
    if(group) scene.remove(group); group=new THREE.Group(); scene.add(group); cars=[]; const d=worlds[world]; scene.background=new THREE.Color(d.sky); scene.fog=new THREE.Fog(d.sky,12,36);
    box(32,.2,32,d.ground,[0,0,-7]);
    billboard(d.image,[0,6,-17],[12,7],'reference');
    if(world==='castle'){ box(6,4,1,0x8e8990,[-5,0,-9]); box(6,4,1,0x8e8990,[5,0,-9]); box(10,3,.8,0xb2a9a1,[0,0,-9]); [-5,5].forEach(x=>{const roof=new THREE.Mesh(new THREE.ConeGeometry(1.8,3,5),mat(0x713e54));roof.position.set(x,5,-9);group.add(roof);}); }
    if(world==='hotel'){ box(18,.35,1.2,0xa8734d,[0,0,-8]); for(let i=-2;i<3;i++){box(.2,4,.2,0xd7b277,[i*3,0,-8]); const l=new THREE.PointLight(0xffae64,1.3,8); l.position.set(i*3,3.4,-7); scene.add(l);} const f=new THREE.Mesh(new THREE.CylinderGeometry(2,2,.25,32),mat(0x7bb4bd));f.position.set(0,.2,-14);group.add(f); }
    if(world==='forest'){ for(let i=0;i<22;i++){ const tx=(Math.random()-.5)*24, tz=-2-Math.random()*18; if(Math.abs(tx)<3.2 && tz>-10) continue; tree(tx,tz); } for(let i=0;i<5;i++) box(3,4,2,0x526f78,[-10+i*5,0,-20]); }
    avatar=box(.72,1.45,.72,0x4c51e8,[0,0,2]); const head=new THREE.Mesh(new THREE.IcosahedronGeometry(.46,1),mat(0xe0a27d)); head.position.set(0,1.95,2); group.add(head); billboard('assets/min-varld/ted-avatar.png',[0,1.35,1.55],[1.35,1.9],'Ted-avatar');
    portal=new THREE.Mesh(new THREE.TorusGeometry(1,.12,8,24),mat(0x8ce8d0)); portal.position.set(7,1,-7); group.add(portal);
    d.spots.forEach((s,i)=>car(s[0],s[1],s[2],i%2?0xd86c5c:0x4e7fe8));
    if(THREE.GLTFLoader){ const loader=new THREE.GLTFLoader(); const worldAsset={castle:'assets/min-varld/castle-hall-hunyuan-shape.glb',hotel:'assets/min-varld/hotel-courtyard-hunyuan-shape.glb',forest:'assets/min-varld/forest-reference-hunyuan-shape.glb'}[world]; loader.load('assets/min-varld/avatar-hunyuan-shape.glb',g=>{avatar.visible=false;fitAsset(g.scene,2.2,[0,0,2]);group.add(g.scene);},undefined,()=>{}); loader.load(worldAsset,g=>{fitAsset(g.scene,10,[0,0,-7]);group.add(g.scene);},undefined,()=>{}); cars.forEach(c=>{loader.load('assets/min-varld/checkpoint-car.glb',g=>{c.visible=false;fitAsset(g.scene,2,[c.position.x,0,c.position.z]);g.scene.userData=c.userData;group.add(g.scene);});}); loader.load('assets/min-varld/portal-marker.glb',g=>{portal.visible=false;fitAsset(g.scene,2,[portal.position.x,0,portal.position.z]);group.add(g.scene);}); }
    title.textContent=d.title; copy.textContent=d.copy; status.textContent='WebGL aktiv · Klicka på en bil eller portalen';
  }
  function next(){world=world==='castle'?'hotel':world==='hotel'?'forest':'castle'; setTabs(); build();}
  function setTabs(){document.querySelectorAll('.world-tab').forEach(b=>b.setAttribute('aria-selected',b.dataset.world===world));}
  function resize(){const r=mount.getBoundingClientRect(); renderer.setSize(r.width,r.height,false); camera.aspect=r.width/r.height; camera.updateProjectionMatrix();}
  function init(){ scene=new THREE.Scene(); camera=new THREE.PerspectiveCamera(52,1,.1,100); camera.position.set(0,5.2,13); renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.15; renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; mount.appendChild(renderer.domElement); const hemi=new THREE.HemisphereLight(0xdbe7ff,0x292016,2.4); scene.add(hemi); const key=new THREE.DirectionalLight(0xffe0b0,3.2); key.position.set(6,10,8); key.castShadow=true; key.shadow.mapSize.set(1024,1024); scene.add(key); const fill=new THREE.DirectionalLight(0x9bbcff,1.4); fill.position.set(-8,5,-10); scene.add(fill); build(); resize(); addEventListener('resize',resize); addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true); addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false); renderer.domElement.onpointerdown=e=>{drag=true;lastX=e.clientX}; addEventListener('pointerup',()=>drag=false); addEventListener('pointermove',e=>{if(drag){yaw-=(e.clientX-lastX)*.005;lastX=e.clientX;}}); renderer.domElement.onclick=e=>{const r=renderer.domElement.getBoundingClientRect(), p=new THREE.Vector2(((e.clientX-r.left)/r.width)*2-1,-((e.clientY-r.top)/r.height)*2+1), ray=new THREE.Raycaster(); ray.setFromCamera(p,camera); const hits=ray.intersectObjects(group.children,true); const hit=hits.find(h=>h.object.parent?.userData?.label||h.object.userData?.label); if(hit){const label=hit.object.parent?.userData?.label||hit.object.userData?.label; status.textContent='Checkpoint: '+label+' · följ bilen';} else if(avatar.position.distanceTo(portal.position)<3) next();}; loop(); }
  function loop(){requestAnimationFrame(loop); const speed=.1; const dz=speed*((keys.w||keys.arrowup)?-1:0)+speed*((keys.s||keys.arrowdown)?1:0); const dx=speed*((keys.a||keys.arrowleft)?-1:0)+speed*((keys.d||keys.arrowright)?1:0); avatar.position.z=Math.max(-5,Math.min(5,avatar.position.z+dz)); avatar.position.x=Math.max(-12,Math.min(12,avatar.position.x+dx)); camera.position.x+=(avatar.position.x-camera.position.x)*.08; camera.position.z+=(avatar.position.z+6-camera.position.z)*.08; camera.position.y=5.2; const lookX=avatar.position.x+Math.sin(yaw)*3, lookZ=avatar.position.z-6-Math.cos(yaw)*2; camera.lookAt(lookX,2.4,lookZ); if(portal) portal.rotation.z+=.02; cars.forEach(c=>c.rotation.y+=.002); renderer.render(scene,camera); }
  document.querySelectorAll('.world-tab').forEach(b=>b.onclick=()=>{world=b.dataset.world;setTabs();build();}); setTabs(); init();
})();
