(() => {
  const mount=document.querySelector('#world-canvas'), status=document.querySelector('#world-status');
  if(!window.THREE){status.textContent='WebGL saknas — använd textalternativen nedan.';return;}
  const worlds={castle:{title:'Slott',copy:'En placeholder för slottet. Gå runt och hitta portalen.',sky:0x171927,ground:0x303342},hotel:{title:'Hotell',copy:'Varm korridor med mjuka ljus och en öppen dörr.',sky:0x211916,ground:0x513b35},forest:{title:'Skog',copy:'Stiliserad skog med berg i fjärran.',sky:0x142229,ground:0x263c34}};
  let world='castle', scene,camera,renderer,group,avatar,portal,keys={},drag=false,lastX=0,yaw=0;
  const title=document.querySelector('#world-title'),copy=document.querySelector('#world-copy');
  function mat(c){return new THREE.MeshStandardMaterial({color:c,roughness:.9})} function box(x,y,z,c){let m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),mat(c));m.position.y=y/2;group.add(m);return m} function tree(x,z){box(.45,2,.45,0x6f4936).position.x=x;let t=new THREE.Mesh(new THREE.ConeGeometry(1.5,3,5),mat(0x416b52));t.position.set(x,3,z);group.add(t)}
  function build(){group?.clear();group=new THREE.Group();scene.background=new THREE.Color(worlds[world].sky);scene.fog=new THREE.Fog(worlds[world].sky,10,32);scene.add(group);box(30,.2,30,worlds[world].ground);if(world==='castle'){box(5,4,1.2,0x8e8990).position.set(-4,0,-6);box(5,4,1.2,0x8e8990).position.set(4,0,-6);box(8,3,.9,0xaaa3a0).position.set(0,0,-6);[[-4,-6],[4,-6]].forEach(p=>{let t=new THREE.Mesh(new THREE.ConeGeometry(1.7,3,5),mat(0x7a4052));t.position.set(p[0],5,p[1]);group.add(t)})}else if(world==='hotel'){for(let i=-2;i<3;i++){box(.2,4,.2,0xd6b98c).position.set(i*3,0,-8);let l=new THREE.PointLight(0xffb66e,1.3,8);l.position.set(i*3,3.2,-7);scene.add(l)}box(16,.2,1,0x9c6e4b).position.set(0,0,-7)}else{for(let i=0;i<18;i++)tree((Math.random()-.5)*22,-3-Math.random()*15);for(let i=0;i<5;i++){let m=box(3,4,2,0x526f78);m.position.set(-10+i*5,0,-15)}} avatar=box(.7,1.4,.7,0x4b4cf0);avatar.position.set(0,0,2);let head=new THREE.Mesh(new THREE.IcosahedronGeometry(.45,1),mat(0xe0a27d));head.position.set(0,1.8,2);group.add(head);portal=new THREE.Mesh(new THREE.TorusGeometry(1, .12,8,24),mat(0x8ce8d0));portal.position.set(0,1,-7);group.add(portal);title.textContent=worlds[world].title;copy.textContent=worlds[world].copy;status.textContent='WebGL aktiv · portal: klicka för nästa värld'}
  function init(){scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(60,1,.1,100);camera.position.set(0,2.2,7);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));mount.append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xb8c7ff,0x252016,2));build();resize();addEventListener('resize',resize);addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);renderer.domElement.onpointerdown=e=>{drag=true;lastX=e.clientX};addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(drag){yaw-=(e.clientX-lastX)*.005;lastX=e.clientX}});renderer.domElement.onclick=()=>{if(Math.abs(avatar.position.z+7)<2){world=world==='castle'?'hotel':world==='hotel'?'forest':'castle';build()}};loop()}
  function resize(){let r=mount.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()} function loop(){requestAnimationFrame(loop);let d=.09*(keys.w||keys.arrowup?-1:0)+(keys.s||keys.arrowdown?1:0);let x=.09*(keys.a||keys.arrowleft?-1:0)+(keys.d||keys.arrowright?1:0);avatar.position.z=Math.max(-5,Math.min(5,avatar.position.z+d));avatar.position.x=Math.max(-10,Math.min(10,avatar.position.x+x));camera.position.x+=(avatar.position.x-camera.position.x)*.08;camera.position.z+=(avatar.position.z+5-camera.position.z)*.08;camera.lookAt(avatar.position.x,1,avatar.position.z-5);portal.rotation.z+=.02;renderer.render(scene,camera)}
  document.querySelectorAll('.world-tab').forEach(b=>b.onclick=()=>{world=b.dataset.world;document.querySelectorAll('.world-tab').forEach(x=>x.setAttribute('aria-selected',x===b));build()});init();
})();
