(() => {
  const mount=document.querySelector('#world-canvas'),status=document.querySelector('#world-status'),title=document.querySelector('#world-title'),copy=document.querySelector('#world-copy');
  if(!window.THREE){status.textContent='WebGL saknas — använd textalternativen nedan.';return;}
  const worlds={
    castle:{title:'Slottet / akademin',copy:'En liten akademigård med torn, valv och fyra rum att upptäcka.',sky:0x182033,ground:0x30394b,image:'assets/min-varld/castle-hall.png',spots:[['Gallery',-7,-6],['Workshop',7,-6],['Library',-7,-14],['Observatory',7,-14]]},
    hotel:{title:'Hotellet',copy:'En varm hotellgård med lobby, balkonger, fontän och bilar.',sky:0x28202a,ground:0x60483f,image:'assets/min-varld/hotel-corridor.png',spots:[['Reception',-7,-6],['Innergård',7,-6],['Fontän',0,-15]]},
    forest:{title:'Skogen',copy:'En stilla low-poly-skog med stig, berg och utsiktsplats.',sky:0x142a30,ground:0x2f5548,image:'assets/min-varld/forest-reference.png',spots:[['Stigen',-7,-6],['Bergsvy',7,-11],['Utsikten',0,-17]]}
  };
  let world=new URLSearchParams(location.search).get('world')||'castle',scene,camera,renderer,group,avatar,portal,cars=[],keys={},drag=false,lastX=0,yaw=0;
  const tex=new THREE.TextureLoader();
  const material=(c,rough=.8)=>new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:.04});
  const add=(mesh,pos=[0,0,0],parent=group)=>{mesh.position.set(...pos);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;};
  const cube=(w,h,d,c,pos=[0,0,0],parent=group)=>add(new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material(c)),[pos[0],pos[1]+h/2,pos[2]],parent);
  const cyl=(r,h,c,pos=[0,0,0],seg=12,parent=group)=>add(new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,seg),material(c)),[pos[0],pos[1]+h/2,pos[2]],parent);
  function billboard(url,pos,size,label){const m=new THREE.Mesh(new THREE.PlaneGeometry(size[0],size[1]),new THREE.MeshBasicMaterial({map:tex.load(url),side:THREE.DoubleSide}));m.position.set(...pos);m.userData.label=label;group.add(m);return m;}
  function tree(x,z){const root=new THREE.Group();root.position.set(x,0,z);cyl(.18,2.5,0x684431,[0,0,0],8,root);add(new THREE.Mesh(new THREE.ConeGeometry(1.35,2.8,8),material(0x377653)),[0,2.2,0],root);add(new THREE.Mesh(new THREE.ConeGeometry(1.05,2.2,8),material(0x4d9365)),[0,3.7,0],root);group.add(root);}
  function car(label,x,z,color){const root=new THREE.Group();root.position.set(x,0,z);root.userData={label};cube(2.1,.45,1.15,color,[0,.25,0],root);cube(1.05,.4,.9,0xdbe5e8,[0,.7,0],root);[-.7,.7].forEach(x=>[-.48,.48].forEach(z=>{const w=add(new THREE.Mesh(new THREE.CylinderGeometry(.2,.2,.16,12),material(0x151820)),[x,.2,z],root);w.rotation.z=Math.PI/2;}));group.add(root);cars.push(root);}
  function avatarModel(){const root=new THREE.Group();root.position.set(0,0,2);root.rotation.y=Math.PI;root.userData.avatar=true;const skin=material(0xc9825d),shirt=material(0x315da8),pants=material(0x26314f),hair=material(0x30251f),shoe=material(0x151a28);cyl(.38,1.05,shirt,[0,.85,0],12,root);add(new THREE.Mesh(new THREE.SphereGeometry(.43,16,12),skin),[0,1.9,0],root);add(new THREE.Mesh(new THREE.SphereGeometry(.45,.45,8),hair),[0,2.14,0],root).scale.set(1, .45, 1);cube(.18,.75,.18,shirt,[-.52,.98,0],root);cube(.18,.75,.18,shirt,[.52,.98,0],root);cube(.24,.9,.25,pants,[-.2,.05,0],root);cube(.24,.9,.25,pants,[.2,.05,0],root);cube(.3,.16,.48,shoe,[-.2,0,-.12],root);cube(.3,.16,.48,shoe,[.2,0,-.12],root);add(new THREE.Mesh(new THREE.SphereGeometry(.055,8,6),material(0x161616)),[-.15,1.98,-.39],root);add(new THREE.Mesh(new THREE.SphereGeometry(.055,8,6),material(0x161616)),[.15,1.98,-.39],root);group.add(root);return root;}
  function castle(){cube(8,4,.8,0xaaa9b5,[-5,0,-10]);cube(8,4,.8,0xaaa9b5,[5,0,-10]);cube(6,5,.9,0x888b9e,[0,0,-10]);[-5,5].forEach(x=>{cyl(1.5,6,0x9d9eae,[x,0,-10],8);add(new THREE.Mesh(new THREE.ConeGeometry(1.7,2.8,8),material(0x7b4059)),[x,6,-10]);});for(let x=-6;x<=6;x+=3)cube(.8,1.1,.15,0x252b45,[x,1,-9.45]);}
  function hotel(){cube(20,.25,10,0x8b6452,[0,0,-9]);cube(20,4,.6,0x79533f,[0,0,-14]);for(let x=-8;x<=8;x+=4){cube(.18,3,.18,0xe0bb78,[x,0,-13.5]);cube(3.2,.16,.8,0xb47e58,[x,2.8,-13.5]);}const f=cyl(2,.3,0x77b7bb,[0,0,-17],24);add(new THREE.Mesh(new THREE.TorusGeometry(1.2,.09,8,24),material(0xd5f1ef)),[0,.35,-17]);}
  function forest(){for(let i=0;i<24;i++){const x=(Math.random()-.5)*25,z=-2-Math.random()*20;if(Math.abs(x)<3&&z>-11)continue;tree(x,z);}for(let i=0;i<5;i++)cube(3,3,2,0x596d72,[-10+i*5,0,-21]);}
  function build(){if(group)scene.remove(group);group=new THREE.Group();scene.add(group);cars=[];const d=worlds[world];scene.background=new THREE.Color(d.sky);scene.fog=new THREE.Fog(d.sky,18,42);cube(34,.18,34,d.ground,[0,0,-9]);billboard(d.image,[0,6,-22],[10,6],'reference');if(world==='castle')castle();if(world==='hotel')hotel();if(world==='forest')forest();avatar=avatarModel();portal=add(new THREE.Mesh(new THREE.TorusGeometry(1.05,.13,10,28),material(0x8ce8d0)),[7,1,-8]);d.spots.forEach((s,i)=>car(s[0],s[1],s[2],i%2?0xd86c5c:0x4e7fe8));title.textContent=d.title;copy.textContent=d.copy;status.textContent='WebGL aktiv · Klicka på en bil eller portalen';}
  function next(){world=world==='castle'?'hotel':world==='hotel'?'forest':'castle';setTabs();build();}
  function setTabs(){document.querySelectorAll('.world-tab').forEach(b=>b.setAttribute('aria-selected',b.dataset.world===world));}
  function resize(){const r=mount.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}
  function init(){scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(48,1,.1,100);camera.position.set(0,4.8,12);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;mount.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xdce9ff,0x263020,2.2));const key=new THREE.DirectionalLight(0xffddb0,3.2);key.position.set(7,11,9);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key);const fill=new THREE.DirectionalLight(0x9dbbff,1.2);fill.position.set(-8,5,-12);scene.add(fill);build();resize();addEventListener('resize',resize);addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);renderer.domElement.onpointerdown=e=>{drag=true;lastX=e.clientX};addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(drag){yaw-=(e.clientX-lastX)*.005;lastX=e.clientX;}});renderer.domElement.onclick=e=>{const r=renderer.domElement.getBoundingClientRect(),p=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(p,camera);const hit=ray.intersectObjects(group.children,true).find(h=>h.object.parent?.userData?.label||h.object.userData?.label);if(hit)status.textContent='Checkpoint: '+(hit.object.parent?.userData?.label||hit.object.userData.label)+' · följ bilen';else if(avatar.position.distanceTo(portal.position)<3)next();};loop();}
  function loop(){requestAnimationFrame(loop);const speed=.1,dz=speed*((keys.w||keys.arrowup)?-1:0)+speed*((keys.s||keys.arrowdown)?1:0),dx=speed*((keys.a||keys.arrowleft)?-1:0)+speed*((keys.d||keys.arrowright)?1:0);avatar.position.z=Math.max(-4,Math.min(5,avatar.position.z+dz));avatar.position.x=Math.max(-12,Math.min(12,avatar.position.x+dx));camera.position.x+=(avatar.position.x-camera.position.x)*.08;camera.position.z+=(avatar.position.z+7-camera.position.z)*.08;camera.position.y=4.8;camera.lookAt(avatar.position.x+Math.sin(yaw)*2,1.7,avatar.position.z-7);if(portal)portal.rotation.z+=.02;renderer.render(scene,camera);}
  document.querySelectorAll('.world-tab').forEach(b=>b.onclick=()=>{world=b.dataset.world;setTabs();build();});setTabs();init();
})();