(() => {
  const button = document.getElementById('realtime-toggle'); const status = document.getElementById('realtime-status'); if (!button || !status) return;
  const endpoint = 'wss://ryzen-ted.tailfbfb1a.ts.net:9443/control-api/voice';
  let socket, stream, input, processor, sink, ctx, playing = [], pcmQueue = [], playingNow = false;
  const setStatus = s => { status.textContent = s; };
  const stopAudio = () => { playing.forEach(x => { try { x.stop(); } catch (_) {} }); playing = []; pcmQueue = []; playingNow = false; };
  const downsample = (input, from, to) => { if (from === to) return input; const ratio = from / to, out = new Int16Array(Math.round(input.length / ratio)); for (let i=0;i<out.length;i++){let sum=0,n=0,start=Math.floor(i*ratio),end=Math.min(Math.floor((i+1)*ratio),input.length);for(let j=start;j<end;j++){sum+=input[j];n++;}out[i]=Math.max(-1,Math.min(1,sum/(n||1)))*0x7fff;} return out; };
  const playNext = () => { if (playingNow || !pcmQueue.length || !ctx) return; playingNow=true; const bytes=pcmQueue.shift(), samples=new Int16Array(bytes.buffer,bytes.byteOffset,Math.floor(bytes.byteLength/2)), buffer=ctx.createBuffer(1,samples.length,24000), channel=buffer.getChannelData(0); for(let i=0;i<samples.length;i++) channel[i]=samples[i]/32768; const source=ctx.createBufferSource(); source.buffer=buffer; source.connect(ctx.destination); playing.push(source); source.onended=()=>{playing=playing.filter(x=>x!==source);playingNow=false;playNext();}; source.start(); };
  const close = () => { stopAudio(); processor?.disconnect(); sink?.disconnect(); input?.disconnect(); stream?.getTracks().forEach(t=>t.stop()); socket?.close(); processor=sink=input=stream=socket=null; button.setAttribute('aria-pressed','false'); button.textContent='Starta Sofia'; setStatus('Redo – tryck för att starta'); };
  const start = async () => { button.disabled=true; setStatus('Ansluter…'); try { stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}}); ctx=new AudioContext(); await ctx.resume(); input=ctx.createMediaStreamSource(stream); processor=ctx.createScriptProcessor(2048,1,1); sink=ctx.createGain(); sink.gain.value=0; socket=new WebSocket(endpoint); socket.binaryType='arraybuffer'; socket.onopen=()=>{button.disabled=false;button.setAttribute('aria-pressed','true');button.textContent='Stoppa Sofia';setStatus('Sofia lyssnar…');}; socket.onmessage=e=>{if(typeof e.data==='string'){const d=JSON.parse(e.data);if(d.type==='speech_started')setStatus('Lyssnar…');if(d.type==='transcript')setStatus('Sofia tänker…');if(d.type==='sofia_started'||d.type==='sofia_text')setStatus('Sofia svarar…');if(d.type==='interrupted'){stopAudio();setStatus('Lyssnar…');}if(d.type==='turn_complete')setStatus('Sofia lyssnar…');if(d.type==='error')setStatus('Voicefel');}else{pcmQueue.push(new Int16Array(e.data));playNext();}}; socket.onerror=()=>setStatus('Voicefel — kontrollera Tailscale'); socket.onclose=()=>{if(socket)close();}; processor.onaudioprocess=e=>{if(socket?.readyState===WebSocket.OPEN)socket.send(downsample(e.inputBuffer.getChannelData(0),ctx.sampleRate,16000));}; input.connect(processor); processor.connect(sink); sink.connect(ctx.destination); } catch(e){setStatus(`Kunde inte starta: ${e.message}`);close();button.disabled=false;} };
  button.addEventListener('click',()=>button.getAttribute('aria-pressed')==='true'?close():start());
})();
