(() => {
  const mount=document.querySelector('#city-canvas'); if(!mount||!window.CityAgents)return;
  const A=window.CityAgents, Memory=window.CityMemory, state=A.createSimulationState();
  // The public client is a read-only city viewer; it must never call a model endpoint.
  A.askQwen=async()=>null;
  // Qwen is server-side only. The browser receives sanitized city state.
  state.qwenEndpoint='';
  const CITY_API='https://5.175.249.12.nip.io/city/api/city';
  async function syncCity(){try{const response=await fetch(CITY_API,{cache:'no-store'});if(!response.ok)return;const remote=await response.json();if(!Array.isArray(remote.agents)||remote.agents.length!==5)return;state.minute=remote.minute;state.day=remote.day;state.weather=remote.weather;state.lastQwen=performance.now();remote.agents.forEach((remoteAgent,i)=>Object.assign(state.agents[i],remoteAgent));state.events=remote.events||state.events;renderAgentList();renderDetail();renderEvents();$('#model-status').textContent=remote.qwen_configured?'Stadens motor · aktiv':'Stadens motor · lokal drift';}catch(_){/* local simulation remains a graceful fallback */}}
  syncCity();setInterval(syncCity,15000);
  const places={home:[0,0],plaza:[0,0],library:[-7,-5],workshop:[7,-5],school:[-7,0],garden:[7,0],hall:[0,-5],cafe:[0,3]};
  const $=s=>document.querySelector(s), stage=document.querySelector('.sim-stage');
  $('#new-law').onclick=()=>{const proposals=['Nattbuss till biblioteket','Solpaneler på rådhusets tak','Lugnare timmar på torget'];const title=proposals[state.laws.length%proposals.length];const author=state.agents.find(a=>a.id===selected)?.name||'Staden';state.laws.unshift({id:`law-${Date.now()}`,title,author,yes:0,no:0,status:'pågående'});state.events.unshift({time:A.clock(state.minute),text:`${title} föreslogs i rådhuset.`});renderLaws();renderEvents();};
  let scene,camera,renderer,city,avatarMeshes=[],rain,lights=[],sunLight,last=performance.now(),simAccum=0,selected=state.selected, qwenIndex=0, yaw=0, dragging=false,lastX=0;
  let directorIndex=0,directorChangedAt=performance.now(),directorHoldUntil=0;
  const mat=(c,r=.85)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:.05});
  const add=(o,p=[0,0,0],parent=city)=>{o.position.set(...p);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;};
  const box=(w,h,d,c,p,parent=city)=>add(new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c)),[p[0],p[1]+h/2,p[2]],parent);
  const cyl=(r,h,c,p,parent=city)=>add(new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,10),mat(c)),[p[0],p[1]+h/2,p[2]],parent);
  function building(x,z,w,d,h,c,label){box(w,h,d,c,[x,0,z]);for(let yy=1;yy<h;yy+=1.4)for(let xx=x-w/2+1;xx<x+w/2;xx+=1.5)box(.42,.36,.04,0xf3c878,[xx,yy,z-d/2-.03]);const sign=box(Math.min(w-1,4),.4,.06,0x1e2a41,[x,h*.55,z-d/2-.08]);sign.userData.label=label;}
  function tree(x,z){cyl(.16,1.5,0x5e4632,[x,0,z]);add(new THREE.Mesh(new THREE.IcosahedronGeometry(1.05,1),mat(0x28614e)),[x,2,z]);add(new THREE.Mesh(new THREE.IcosahedronGeometry(.7,1),mat(0x3d8a68)),[x-.2,2.8,z+.1]);}
  function lamp(x,z){cyl(.035,2.4,0x48536a,[x,0,z]);add(new THREE.Mesh(new THREE.SphereGeometry(.15,8,6),new THREE.MeshBasicMaterial({color:0xf3c878})),[x,2.5,z]);const l=new THREE.PointLight(0xf3c878,1.2,5);l.position.set(x,2.4,z);scene.add(l);lights.push(l);}
  function makeAvatar(agent){const g=new THREE.Group();g.userData.id=agent.id;g.position.set(agent.home[0],0,agent.home[1]);const body=mat(agent.color), skin=mat(0xd0926d), dark=mat(0x20273b);cyl(.32,.85,agent.color,[0,.55,0],g);add(new THREE.Mesh(new THREE.SphereGeometry(.35,14,10),skin),[0,1.65,0],g);add(new THREE.Mesh(new THREE.SphereGeometry(.37,14,8),dark),[0,1.87,0],g).scale.set(1,.42,1);box(.17,.55, .17,body,[-.43,.45,0],g);box(.17,.55,.17,body,[.43,.45,0],g);box(.2,.7,.2,dark,[-.16,0,0],g);box(.2,.7,.2,dark,[.16,0,0],g);const halo=new THREE.Mesh(new THREE.RingGeometry(.48,.53,24),new THREE.MeshBasicMaterial({color:agent.color,transparent:true,opacity:.55,side:THREE.DoubleSide}));halo.rotation.x=-Math.PI/2;halo.position.y=.03;g.add(halo);city.add(g);return g;}
  function loadAvatarMesh(agent,holder){if(!THREE.GLTFLoader)return;const loader=new THREE.GLTFLoader();loader.load('assets/min-varld/avatar-hunyuan-optimized.glb',gltf=>{const model=gltf.scene.clone(true);model.traverse(o=>{if(o.isMesh){const meshBounds=new THREE.Box3().setFromObject(o),meshSize=meshBounds.getSize(new THREE.Vector3());if(meshSize.z<.08&&meshSize.x>meshSize.y*1.35)o.visible=false;o.castShadow=true;o.receiveShadow=true;if(o.material?.clone){o.material=o.material.clone();o.material.roughness=.82;o.material.metalness=.02;o.material.emissive?.setHex(0x000000);}}});const bounds=new THREE.Box3().setFromObject(model),size=bounds.getSize(new THREE.Vector3()),scale=1.65/(Math.max(size.x,size.y,size.z)||1);model.scale.setScalar(scale);const fitted=new THREE.Box3().setFromObject(model);model.position.y=-fitted.min.y;holder.children.forEach(child=>{child.visible=false;});holder.add(model);},undefined,()=>{});}
  function buildCity(){city=new THREE.Group();scene.add(city);box(32,.15,27,0x111b2a,[0,0,-2]);box(3,.05,27,0x283345,[-1.5,.16,-2]);box(32,.05,3,0x283345,[0,.16,-2]);box(10,.04,8,0x1c3540,[0,.18,0]);building(-7,-8,6,3,3.6,0x263853,'BIBLIOTEK');building(7,-8,6,3,3.2,0x3c3043,'VERKSTAD');building(-7,-2,5,3,2.7,0x30475a,'SKOLA');building(7,-2,5,3,2.9,0x4a3840,'RÅDHUS');building(0,6,18,2.5,2.4,0x202d42,'BOSTÄDER');for(let x=-13;x<=13;x+=4.3){tree(x,4);lamp(x,-1);lamp(x,-9);}for(let x=-9;x<=9;x+=3)lamp(x,1);const water=new THREE.Mesh(new THREE.CircleGeometry(2.6,32),new THREE.MeshStandardMaterial({color:0x2a7c89,roughness:.2,metalness:.4}));water.rotation.x=-Math.PI/2;water.position.set(0,.22,-2);city.add(water);state.agents.forEach(a=>{const avatar=makeAvatar(a);avatarMeshes.push(avatar);loadAvatarMesh(a,avatar);});createParticles();}
  function createParticles(){const geo=new THREE.BufferGeometry(),pos=[];for(let i=0;i<420;i++)pos.push((Math.random()-.5)*30,Math.random()*11,(Math.random()-.5)*25-3);geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));rain=new THREE.Points(geo,new THREE.PointsMaterial({color:0x9ec7e6,size:.055,transparent:true,opacity:.7}));rain.visible=false;scene.add(rain);}
  function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x0d1b2e);scene.fog=new THREE.Fog(0x0d1b2e,18,38);camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(0,5,12);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;mount.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0x9dbfe8,0x122016,1.15));sunLight=new THREE.DirectionalLight(0xffddb2,2.2);sunLight.castShadow=true;sunLight.shadow.mapSize.set(1024,1024);scene.add(sunLight);buildCity();resize();addEventListener('resize',resize);bind();loop();}
  function resize(){const r=mount.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}
  function bind(){document.querySelectorAll('.agent-card').forEach(x=>x.onclick=()=>{selected=x.dataset.id;renderAgentList();renderDetail();});$('#pause-btn').onclick=()=>{state.paused=!state.paused;$('#pause-btn').textContent=state.paused?'Fortsätt':'Pausa';};document.querySelectorAll('.speed').forEach(x=>x.onclick=()=>{state.speed=+x.dataset.speed;document.querySelectorAll('.speed').forEach(b=>b.classList.toggle('active',b===x));});document.querySelectorAll('.weather').forEach(x=>x.onclick=()=>{state.weather=x.dataset.weather;document.querySelectorAll('.weather').forEach(b=>b.classList.toggle('active',b===x));rain.visible=state.weather!=='clear';});document.querySelectorAll('.time-mode').forEach(x=>x.onclick=()=>{state.minute=x.dataset.mode==='day'?12*60:22*60;document.querySelectorAll('.time-mode').forEach(b=>b.classList.toggle('active',b===x));});$('#save-endpoint').onclick=()=>{state.qwenEndpoint=$('#qwen-endpoint').value;localStorage.setItem('city-qwen-endpoint',state.qwenEndpoint);askBrains(true);};$('#ask-agent').onclick=askSelected;$('#agent-question').onkeydown=e=>{if(e.key==='Enter')askSelected();};mount.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX});addEventListener('pointerup',()=>dragging=false);addEventListener('pointermove',e=>{if(dragging){yaw+=(e.clientX-lastX)*.004;lastX=e.clientX;}});}
  function renderAgentList(){const list=$('#agent-list');list.innerHTML=state.agents.map(a=>`<button class="agent-card ${a.id===selected?'selected':''}" data-id="${a.id}" style="--agent-color:${a.color};--need:${100-a.needs.sleep}%"><span class="agent-orb"></span><strong>${a.name}</strong><small>${a.online?'Qwen · ':''}${a.actionLabel}</small><span class="agent-status"><i></i></span></button>`).join('');list.querySelectorAll('.agent-card').forEach(x=>x.onclick=()=>{selected=x.dataset.id;renderAgentList();renderDetail();});$('#active-count').textContent=`${state.agents.filter(a=>a.needs.sleep<78).length} vakna`;}
  function renderDetail(){const a=state.agents.find(x=>x.id===selected)||state.agents[0];const relations=Object.entries(a.relationship).filter(([id])=>id!==a.id).sort((x,y)=>y[1]-x[1]).slice(0,3).map(([id,v])=>`${id[0].toUpperCase()+id.slice(1)} ${v>0?'+'+v:v}`).join(' · ');$('#question-name').textContent=a.name;$('#agent-detail-content').innerHTML=`<div class="agent-hero"><span class="agent-orb" style="--agent-color:${a.color}"></span><div><h2>${a.name}</h2><p>${a.role} · ${a.trait}</p></div></div><div class="thought">“${a.thought}”</div><div class="needs">${Object.entries(a.needs).map(([k,v])=>`<span class="need" style="--agent-color:${a.color};--value:${v}%"><b>${({sleep:'sömn',hunger:'mat',social:'socialt',curiosity:'nyfiken',purpose:'mening'})[k]}</b><i></i></span>`).join('')}</div><p class="panel-meta" style="margin-top:14px">${a.name} ${a.actionLabel} · ${a.place}</p><p class="agent-knowledge">Relationer: ${relations||'nya möten'}<br>Senaste kunskap: ${a.knowledge?.[0]||'lyssnar på staden'}</p>`;}
  function renderLaws(){ $('#law-list').innerHTML=state.laws.map(l=>`<div class="law"><div class="law-title">${l.title}</div><div class="law-meta"><span>${l.author} · ${l.status}</span><span class="law-vote" data-law="${l.id}">Ja ${l.yes} · Nej ${l.no}</span></div></div>`).join('');document.querySelectorAll('.law-vote').forEach(x=>x.onclick=()=>{const l=state.laws.find(y=>y.id===x.dataset.law);l.yes++;l.status=l.yes>=3?'antagen':'pågående';state.events.unshift({time:A.clock(state.minute),text:`${l.title} fick en ny röst.`});renderLaws();renderEvents();});}
  function renderEvents(){$('#event-list').innerHTML=state.events.slice(0,6).map(e=>`<div class="event"><time>${e.time}</time><span>${e.text}</span></div>`).join('');}
  function updateDirector(now){const interval=24000;if(now-directorChangedAt>interval&&!dragging){directorIndex=(directorIndex+1)%state.agents.length;directorChangedAt=now;}const focus=state.agents[directorIndex]||state.agents[0],mesh=avatarMeshes[directorIndex];if(!mesh)return;const focusPoint=new THREE.Vector3(mesh.position.x,1.2,mesh.position.z);const distance=window.innerWidth<680?5.8:7.4;const desired=new THREE.Vector3(focusPoint.x+Math.sin(yaw)*distance,focusPoint.y+2.15,focusPoint.z+Math.cos(yaw)*distance);camera.position.lerp(desired,.055);camera.lookAt(focusPoint);$('#scene-copy').textContent=`Följer ${focus.name} · ${focus.actionLabel}`;}
  function updateScene(){state.agents.forEach((a,i)=>{const m=avatarMeshes[i],t=places[a.place]||a.home;if(!m)return;const dx=t[0]-m.position.x,dz=t[1]-m.position.z,distance=Math.hypot(dx,dz);m.position.x+=dx*.012*state.speed;m.position.z+=dz*.012*state.speed;m.position.y=Math.abs(Math.sin(performance.now()/260+i))*.045;if(distance>.12){m.rotation.y=Math.atan2(dx,dz);}if(distance>.8){a._stuckTicks=(a._stuckTicks||0)+1;}else{a._stuckTicks=0;}if(a._stuckTicks>360&&Memory){Memory.recoverIfStuck(a,{hour:(state.minute%1440)/60});a._stuckTicks=0;}});const hour=(state.minute%1440)/60,solar=Math.max(0,Math.sin((hour-6)/12*Math.PI)),night=solar<.12;scene.background.lerp(new THREE.Color(night?0x08101d:solar<.45?0x304968:0x5c829c),.03);scene.fog.color.copy(scene.background);if(sunLight){sunLight.position.set(Math.cos((hour-12)/24*Math.PI*2)*14,3+solar*14,Math.sin((hour-12)/24*Math.PI*2)*14);sunLight.intensity=.25+solar*2.2;sunLight.color.set(solar<.3?0x9ba9d8:0xffddb2);}lights.forEach(l=>l.intensity=night?1.8:.45);$('#city-time').textContent=A.clock(state.minute);$('#city-weather').textContent=({clear:'Klart · 14°',rain:'Regn · 11°',snow:'Snö · 2°'})[state.weather];$('#scene-day').textContent=`DAG ${state.day} · ${night?'NATT':solar<.45?'SKYMNING':'DAG'}`;if(rain){rain.visible=state.weather!=='clear';rain.rotation.y+=.0008;}}
  function runModelFor(a){return A.askQwen(a,{time:A.clock(state.minute),needs:a.needs,nearby:state.agents.filter(x=>x.id!==a.id).map(x=>x.name),relationships:a.relationship,last:a.memory[0]},state.qwenEndpoint).then(reply=>{if(reply){a.online=true;a.thought=reply.thought;A.startAction(a,reply.action);$('#model-status').textContent=`Qwen3.8 · ${state.agents.filter(x=>x.online).length}/5 anslutna`;$('#model-dot').style.background='#75d6c7';}else{$('#model-status').textContent='Lokal hjärna · utility fallback';}return !!reply;});}
  function askBrains(force=false){const a=force?(state.agents.find(x=>x.id===selected)||state.agents[0]):state.agents[qwenIndex++%state.agents.length];if(!force&&performance.now()-state.lastQwen<18000)return;state.lastQwen=performance.now();runModelFor(a);}
  async function askSelected(){const input=$('#agent-question'),q=input.value.trim();if(!q)return;const a=state.agents.find(x=>x.id===selected);$('#conversation-answer').textContent='Tänker…';input.value='';try{const response=await fetch(`${CITY_API}/conversation`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agent_id:a.id,question:q})});const result=await response.json();const answer=result.answer||'Jag behöver lite tid att tänka.';Memory?.rememberConversation(a,'besökaren',q);Memory?.rememberConversation(a,'besökaren',answer);$('#conversation-answer').textContent=answer;}catch(_){$('#conversation-answer').textContent='Staden svarar inte just nu — prova igen om en stund.';}}
  function loop(now=performance.now()){requestAnimationFrame(loop);const dt=Math.min(100,now-last);last=now;simAccum+=dt;if(simAccum>700){A.tickAgents(state,1);simAccum=0;localStorage.setItem('city-simulation-state',JSON.stringify({...state,lastQwen:0}));renderAgentList();renderDetail();renderEvents();if(state.weather==='rain'&&Math.random()<.1)state.events.unshift({time:A.clock(state.minute),text:'Regnet börjar falla över torget.'});}updateScene();updateDirector(now);renderer.render(scene,camera);if(performance.now()-state.lastQwen>18000)askBrains();}
  $('#qwen-endpoint').value=state.qwenEndpoint;renderAgentList();renderDetail();renderLaws();renderEvents();try{if(!window.THREE)throw Error();init();}catch(e){$('#webgl-fallback').style.display='block';$('#webgl-fallback').textContent='WebGL saknas — simulatorns textläge är aktivt.';}$('#save-endpoint').addEventListener('click',()=>state.agents.forEach((agent,index)=>setTimeout(()=>runModelFor(agent),index*2200)));
})();
