import {PARTIES,TOPICS,scoreAnswers,buildProfile,matchConfidence,PARTY_SOURCES} from './valkompass-model.mjs';
const names={S:'Socialdemokraterna',M:'Moderaterna',SD:'Sverigedemokraterna',V:'Vänsterpartiet',C:'Centerpartiet',MP:'Miljöpartiet',KD:'Kristdemokraterna',L:'Liberalerna'};
const colors={S:'#e11d48',M:'#2563eb',SD:'#1d4ed8',V:'#ef4444',C:'#16a34a',MP:'#15803d',KD:'#0ea5e9',L:'#60a5fa'};
const labels={ekonomi:'Ekonomi & skatter',välfärd:'Välfärd & vård',klimat:'Klimat & natur',migration:'Migration & integration',trygghet:'Brott & trygghet',energi:'Energi',europa:'EU & omvärld',demokrati:'Demokrati & rättsstat',skola:'Skola & kunskap',arbetsmarknad:'Jobb & arbetsmarknad',bostad:'Bostad',försvar:'Försvar & beredskap',jämställdhet:'Jämställdhet & frihet',landsbygd:'Landsbygd & hela landet'};
const texts={ekonomi:'Sänk skatten även om välfärden får mindre utrymme.',välfärd:'Staten ska ta större ansvar för vård och skola.',klimat:'Sverige ska skärpa klimatpolitiken även om det kostar mer.',migration:'Sverige bör ha en mer generös migrationspolitik.',trygghet:'Hårdare straff är viktigare än förebyggande insatser.',energi:'Kärnkraft bör byggas ut som del av energimixen.',europa:'Sverige bör fördjupa samarbetet inom EU.',demokrati:'Skyddet för grundläggande fri- och rättigheter ska väga tyngst.',skola:'Skolan ska ha mer statligt ansvar och tydligare kunskapskrav.',arbetsmarknad:'Det ska bli enklare och billigare för företag att anställa.',bostad:'Staten bör investera mer i bostäder och hålla hyror nere.',försvar:'Sverige bör prioritera ett starkare totalförsvar även om andra utgifter minskar.',jämställdhet:'Politiken ska aktivt minska skillnader mellan kvinnor och män.',landsbygd:'Hela landet ska ha likvärdig service även om det kostar mer.'};
const sources={ekonomi:'https://moderaterna.se/valmanifest-2026/',välfärd:'https://www.socialdemokraterna.se/val-2026',klimat:'https://www.mp.se/valmanifest2026/',migration:'https://www.liberalerna.se/valmanifest-2026/8-ett-sverige-som-haller-ihop',trygghet:'https://moderaterna.se/valmanifest-2026/',energi:'https://kristdemokraterna.se/var-politik/val-2026/valmanifest',europa:'https://www.liberalerna.se/wp-content/uploads/liberalernas-valmanifest-2026-40s-komprimerad.pdf',demokrati:'https://val2026.centerpartiet.se/',skola:'https://www.liberalerna.se/var-politik-valet-2026',arbetsmarknad:'https://val2026.centerpartiet.se/',bostad:'https://www.mp.se/valmanifest2026/',försvar:'https://moderaterna.se/valmanifest-2026/',jämställdhet:'https://www.mp.se/valmanifest2026/',landsbygd:'https://val2026.centerpartiet.se/'};
const challenges={S:'Skulle du kunna rösta på ett parti som prioriterar hårdare migrationspolitik även om du själv föredrar större öppenhet?',M:'Skulle du kunna acceptera ett parti som vill sänka skatter även om fördelningen mellan grupper blir mer ojämn?',SD:'Skulle du kunna rösta på ett parti som driver en betydligt stramare migrationspolitik även om tonen i debatten blir hårdare?',V:'Skulle du kunna acceptera ett parti som vill höja skatter för höginkomsttagare för att finansiera välfärden?',C:'Skulle du kunna rösta på ett parti som prioriterar marknadslösningar även om staten får mindre direkt kontroll?',MP:'Skulle du kunna acceptera ett parti som vill skärpa klimatpolitiken även om vardagskostnader påverkas?',KD:'Skulle du kunna rösta på ett parti som prioriterar familj och civilsamhälle framför vissa statliga lösningar?',L:'Skulle du kunna acceptera ett parti som vill fördjupa EU-samarbetet även om mer beslut flyttas till EU-nivå?'};
let phase=0,index=0,answers={},priorities=Object.fromEntries(TOPICS.map(t=>[t,3]));const app=document.querySelector('[data-app]'),out=document.querySelector('[data-step]');
document.querySelector('[data-start]').onclick=()=>{document.querySelector('.compass-hero').hidden=true;app.hidden=false;render()};
const items=()=>phase===0||phase===1?TOPICS:PARTIES;const total=()=>TOPICS.length*2+PARTIES.length;
function render(){const done=phase===0?index:phase===1?TOPICS.length+index:phase===2?TOPICS.length*2+index:total();document.querySelector('[data-progress-bar]').style.width=Math.min(100,done/total()*100)+'%';document.querySelector('[data-step-count]').textContent=`${Math.min(done+1,total())} / ${total()}`;document.querySelector('[data-step-label]').textContent=['Prioriteringar','Sakfrågor','Kompromisser','Resultat'][phase];if(phase===0)priority();else if(phase===1)issue();else if(phase===2)accept();else result()}
function shell(title,desc,body,next='Nästa'){out.innerHTML=`<div class="question-card glass"><h2>${title}</h2><p>${desc}</p>${body}<div class="actions">${index||phase?'<button class="back" data-back>← Tillbaka</button>':'<span></span>'}<button data-next>${next} →</button></div></div>`;document.querySelector('[data-back]')?.addEventListener('click',()=>{if(index)index--;else{phase--;index=phase===0||phase===1?TOPICS.length-1:PARTIES.length-1}render()});document.querySelector('[data-next]').onclick=()=>{if(index<items().length-1)index++;else{phase++;index=0}render()}}
function choices(key,vals,labelsFor){return `<div class="answer-grid">${vals.map((v,i)=>`<button type="button" data-answer="${key}" data-value="${v}" aria-pressed="${String(answers[key]??priorities[key])===String(v)}" class="${String(answers[key]??priorities[key])===String(v)?'selected':''}">${labelsFor[i]}</button>`).join('')}</div>`}
function priority(){const t=TOPICS[index];shell(`Hur viktig är ${labels[t]}?`,'Välj hur mycket detta område ska väga i ditt resultat.',`<div class="topic-prompt"><b>${labels[t]}</b><small>Fyra nivåer — från mindre viktigt till avgörande.</small>${choices(t,[1,2,3,4],['Mindre viktigt','Ganska viktigt','Viktigt','Avgörande'])}</div>`);wire(v=>priorities[v.key]=+v.value)}
function issue(){const t=TOPICS[index];shell(labels[t],`Fråga ${index+1} av ${TOPICS.length}. <a href="${sources[t]}" target="_blank" rel="noopener">Jämför med underlag ↗</a>`,`<div class="topic-prompt"><b>${texts[t]}</b><small>Fyra svarsalternativ.</small>${choices(t,[-2,-1,1,2],['Helt emot','Lutar emot','Lutar för','Helt för'])}</div>`);wire(v=>answers[v.key]=+v.value)}
function accept(){const p=PARTIES[index];shell(names[p],`Kontrollfråga ${index+1} av ${PARTIES.length}. Samma typ av fråga visas för alla partier.`,`<div class="topic-prompt"><b>${challenges[p]}</b><small>Fyra svarsalternativ — svaret påverkar endast detta parti.</small>${choices('accept_'+p,[-2,-1,1,2],['Inte alls','Tveksamt','Ganska möjligt','Absolut'])}</div>`,'Visa resultat');wire(v=>answers[v.key]=+v.value)}
function wire(set){document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{document.querySelectorAll(`[data-answer="${b.dataset.answer}"]`).forEach(x=>{x.classList.remove('selected');x.setAttribute('aria-pressed','false')});b.classList.add('selected');b.setAttribute('aria-pressed','true');set({key:b.dataset.answer,value:b.dataset.value})})}
function result(){const scores=scoreAnswers(answers,priorities),sorted=Object.entries(scores).sort((a,b)=>b[1]-a[1]),profile=buildProfile(answers,priorities,{}),confidence=matchConfidence(scores),top=profile.priorities.filter(x=>x.value>0).slice(0,3),rationale=top.length?top.map(x=>`${labels[x.key]} (prioritet ${x.value}/5, ${profile.stance[x.key]})`).join(', '):'inga prioriteringar';out.innerHTML=`<div class="question-card glass"><h2>Ditt resultat</h2><p>Din högsta matchning är <b>${names[sorted[0][0]]}</b> på ${sorted[0][1]} %. Säkerheten är <b>${confidence.label}</b> (skillnad ${confidence.gap} procentenheter till tvåan). Det är en matchning, inte ett besked om hur du ska rösta.</p><div class="result-grid"><div class="result-card"><h3>Alla partier</h3>${sorted.map(([p,s])=>`<div class="match"><span class="party-mark" style="background:${colors[p]}">${p}</span><span><b>${names[p]}</b> · <a href="${PARTY_SOURCES[p]}" target="_blank" rel="noopener">underlag ↗</a><span class="match-bar"><span style="width:${s}%"></span></span></span><strong>${s}%</strong></div>`).join('')}</div><div class="result-card"><h3>Din profil</h3><p>Det som vägde tyngst var ${rationale}.</p><p>Acceptansfrågorna visar vilka kompromisser du kan leva med. Ett lågt svar drar ned just det partiet, även om andra sakfrågor matchar.</p><p class="disclaimer">Modellen är ett transparent orienteringsverktyg. Kontrollera alltid aktuella partiprogram, riksdagsbeslut och källor före ett val.</p></div></div></div>`}
