import {PARTIES,TOPICS,scoreAnswers,buildProfile,matchConfidence} from './valkompass-model.mjs';
const names={S:'Socialdemokraterna',M:'Moderaterna',SD:'Sverigedemokraterna',V:'Vänsterpartiet',C:'Centerpartiet',MP:'Miljöpartiet',KD:'Kristdemokraterna',L:'Liberalerna'};
const colors={S:'#e11d48',M:'#2563eb',SD:'#1d4ed8',V:'#ef4444',C:'#16a34a',MP:'#16a34a',KD:'#0ea5e9',L:'#60a5fa'};
const labels={ekonomi:'Ekonomi & skatter',välfärd:'Välfärd & vård',klimat:'Klimat & natur',migration:'Migration & integration',trygghet:'Brott & trygghet',energi:'Energi',europa:'EU & omvärld',demokrati:'Demokrati & rättsstat'};
const challenges={S:'Skulle du kunna rösta på ett parti som prioriterar hårdare migrationspolitik även om du själv föredrar större öppenhet?',M:'Skulle du kunna acceptera ett parti som vill sänka skatter även om fördelningen mellan grupper blir mer ojämn?',SD:'Skulle du kunna rösta på ett parti som driver en betydligt stramare migrationspolitik även om tonen i debatten blir hårdare?',V:'Skulle du kunna acceptera ett parti som vill höja skatter för höginkomsttagare för att finansiera välfärden?',C:'Skulle du kunna rösta på ett parti som prioriterar marknadslösningar även om staten får mindre direkt kontroll?',MP:'Skulle du kunna acceptera ett parti som vill skärpa klimatpolitiken även om vardagskostnader påverkas?',KD:'Skulle du kunna rösta på ett parti som prioriterar familj och civilsamhälle framför vissa statliga lösningar?',L:'Skulle du kunna acceptera ett parti som vill fördjupa EU-samarbetet även om mer beslut flyttas till EU-nivå?'};
const topicSources={ekonomi:'https://moderaterna.se/valmanifest-2026/',välfärd:'https://www.socialdemokraterna.se/val-2026',klimat:'https://www.mp.se/valmanifest2026/',migration:'https://www.liberalerna.se/valmanifest-2026/8-ett-sverige-som-haller-ihop',trygghet:'https://moderaterna.se/valmanifest-2026/',energi:'https://kristdemokraterna.se/var-politik/val-2026/valmanifest',europa:'https://www.liberalerna.se/wp-content/uploads/liberalernas-valmanifest-2026-40s-komprimerad.pdf',demokrati:'https://val2026.centerpartiet.se/'};
let step=0,answers={},priorities=Object.fromEntries(TOPICS.map(topic=>[topic,3]));const app=document.querySelector('[data-app]'),out=document.querySelector('[data-step]');
document.querySelector('[data-start]').onclick=()=>{document.querySelector('.compass-hero').hidden=true;app.hidden=false;render()};
function render(){const total=step===3?3:3;document.querySelector('[data-progress-bar]').style.width=(Math.min(step+1,total)/total*100)+'%';document.querySelector('[data-step-count]').textContent=`${Math.min(step+1,total)} / ${total}`;document.querySelector('[data-step-label]').textContent=['Prioriteringar','Sakfrågor','Acceptans','Resultat'][step]; if(step===0) prioritiesStep();if(step===1) issuesStep();if(step===2) acceptStep();if(step===3) resultStep()}
function card(title,desc,body){out.innerHTML=`<div class="question-card glass"><h2>${title}</h2><p>${desc}</p>${body}<div class="actions">${step?'<button class="back" data-back>← Tillbaka</button>':'<span></span>'}<button data-next>${step===2?'Visa mitt resultat':'Fortsätt'} →</button></div></div>`;document.querySelector('[data-back]')?.addEventListener('click',()=>{step--;render()});document.querySelector('[data-next]').addEventListener('click',()=>{step++;render()})}
function prioritiesStep(){card('Väg frågorna','Vad vill du att kompassen ska ta störst hänsyn till? Dra reglaget från mindre viktigt till avgörande.',TOPICS.map(t=>`<div class="topic-row"><label>${labels[t]}<small>Prioritet: <output data-out="${t}">3</output> / 5</small></label><input class="range" data-priority="${t}" type="range" min="1" max="5" value="3"></div>`).join(''));document.querySelectorAll('[data-priority]').forEach(x=>x.oninput=()=>{priorities[x.dataset.priority]=+x.value;document.querySelector(`[data-out="${x.dataset.priority}"]`).value=x.value})}
function issuesStep(){card('Ta ställning','Svara även när frågan inte är din hjärtefråga. “Vet ej” påverkar inte matchningen.',TOPICS.map(t=>`<div class="topic-row"><label>${labels[t]}<small>${issueText(t)}</small><small><a href="${topicSources[t]}" target="_blank" rel="noopener">Jämför med partiernas underlag ↗</a></small></label><div class="answer-grid">${[['-2','Emot'],['-1','Svagt emot'],['0','Osäker'],['1','Svagt för'],['2','För']].map(([v,l])=>`<button type="button" data-answer="${t}" data-value="${v}">${l}</button>`).join('')}</div></div>`).join(''));wireAnswers()}
function issueText(t){return {ekonomi:'Sänk skatten även om välfärden får mindre utrymme.',välfärd:'Staten ska ta större ansvar för vård och skola.',klimat:'Sverige ska skärpa klimatpolitiken även om det kostar mer.',migration:'Sverige bör ha en mer generös migrationspolitik.',trygghet:'Hårdare straff är viktigare än förebyggande insatser.',energi:'Kärnkraft bör byggas ut som del av energimixen.',europa:'Sverige bör fördjupa samarbetet inom EU.',demokrati:'Skyddet för grundläggande fri- och rättigheter ska väga tyngst.'}[t]}
function wireAnswers(){document.querySelectorAll('[data-answer]').forEach(b=>{b.setAttribute('aria-pressed','false');b.onclick=()=>{document.querySelectorAll(`[data-answer="${b.dataset.answer}"]`).forEach(x=>{x.classList.remove('selected');x.setAttribute('aria-pressed','false')});b.classList.add('selected');b.setAttribute('aria-pressed','true');answers[b.dataset.answer]=+b.dataset.value}})}
function acceptStep(){card('Dina kompromissgränser','För varje parti: skulle du kunna rösta på ett parti som driver detta? Frågorna är synliga, symmetriska och påverkar bara det parti de gäller.',PARTIES.map(p=>`<div class="topic-row"><label><b>${names[p]}</b><small>${challenges[p]}</small></label><div class="answer-grid">${[['-2','Nej'],['0','Osäker'],['2','Ja']].map(([v,l])=>`<button type="button" data-answer="accept_${p}" data-value="${v}">${l}</button>`).join('')}</div></div>`).join(''));wireAnswers()}
function resultStep(){const scores=scoreAnswers(answers,priorities);const sorted=Object.entries(scores).sort((a,b)=>b[1]-a[1]);const profile=buildProfile(answers,priorities,{});const confidence=matchConfidence(scores);const top=profile.priorities.slice(0,3).filter(x=>x.value>0);const rationale=top.length?top.map(x=>`${labels[x.key]} (prioritet ${x.value}/5, du är ${profile.stance[x.key]})`).join(', '):'inga prioriteringar angavs';const winner=sorted[0][0];out.innerHTML=`<div class="question-card glass"><h2>Ditt resultat</h2><p>Din högsta matchning är <b>${names[winner]}</b> på ${sorted[0][1]} %. Säkerheten är <b>${confidence.label}</b> (skillnad ${confidence.gap} procentenheter till tvåan). Det betyder inte att du “är” partiet, utan att dina svar ligger närmast den positionering som modellen använder.</p><div class="result-grid"><div class="result-card" style="background:rgba(255,255,255,.35)"><h3>Matchning</h3>${sorted.map(([p,s])=>`<div class="match"><span class="party-mark" style="background:${colors[p]}">${p}</span><span><b>${names[p]}</b><span class="match-bar"><span style="width:${s}%"></span></span></span><strong>${s}%</strong></div>`).join('')}</div><div class="result-card" style="background:rgba(255,255,255,.35)"><h3>Så läser du resultatet</h3><p>Det som vägde mest för dig var ${rationale}. Acceptansfrågorna fungerar som en separat spärr: ett lågt svar på en fråga som du själv markerat som viktig kan dra ned ett parti, även om partiet ligger nära dig i andra frågor.</p><p>Din profil är därför mer än en enkel ja/nej-matchning: den beskriver både sakpolitisk riktning, vad du prioriterar och vilka kompromisser du inte vill göra.</p><p class="disclaimer">Metoden är förenklad och källorna till partiernas positioner ska granskas före skarp publicering. Uppdatera alltid frågorna inför ett nytt val.</p></div></div></div>`}
